name: ClymeSkyblockCore
version: 1.0
api-version: 1.16
author: CAMOU
website: https://misi.solutions/
main: solutions.misi.clymeskyblockcore.ClymeSkyblockCore
depend:
  - SuperiorSkyblock2
  - WorldGuard
  - PlaceholderAPI
loadbefore:
  - TAB
  - AuctionGUIPlus
  - DailyBonus
  - UltraMinions

commands:
  spawn:
    description: Teleports you to the spawn
  money:
    description: Shows your current balance
    aliases: [economy, econ, bal, balance, mon]
  playtime:
    description: Shows your current playtime
    aliases: [pt, time, playingtime, onlinetime, ot]
  staffpanel:
    description: Opens the Staffpanel
    aliases: [sp, adminpanel, ap, helperpanel, modmenu, modpanel, adminmenu, staffmenu]
  minions:
    description: Opens the Minions Shop
    aliases: [minion]
  menu:
    description: Opens the Server Menu
    aliases: [help]
  crate:
    description: Teleports you to the crates
    aliases: [crates]
  farming:
    description: Teleports you to the farming world
    aliases: [farm, resources, resource, mining, farmworld]
  message:
    description: Sends a private messsage to another player
    aliases: [msg, pm, mail]
  reply:
    description: Replies to the players you messaged with recently
    aliases: [r]
  tpa:
    description: Sends a teleport request to a player
  tpaccept:
    description: Accepts a teleport request
    aliases: [tpaaccept]
  tpdeny:
    description: Denies a teleport request
  tpahere:
    description: Sends a request to teleport a player to you
  home:
    description: Opens the Home Menu
    aliases: [sethome, homes]
  gamemode:
    description: Changes your or someones current gamemode
    aliases: [gm]
  pvp:
    description: Teleports you to the pvp arena
    aliases: [fight, pvparena, battle]
  day:
    description: Sets the time to day
  night:
    descriptioN: Sets the time to night
  sun:
    description: Sets the weather to sunny
  rain:
    description: Sets the weather to raining
    aliases: [storm, thunder]
  clymecrystal:
    description: Gives you the clyme crystal
  cosmetics:
    description: Opens the cosmetics menu
    aliases: [gadgets, pets, effects, particles]
  baltop:
    description: Teleports you to the richest players leaderboard
    aliases: [moneytop, ecotop, balancetop, economytop]
  donation:
    description: Plays the donation effect to all players
  payouts:
    description: Teleports you to the payouts info
    aliases: [payout]
  tp:
    description: Teleports yourself or others to other players
    aliases: [teleport]
  tphere:
    description: Teleports another player to you
    aliases: [teleporthere, bring]
  fly:
    description: Toggles if you can fly or not
    aliases: [f, flight]
  craft:
    description: Opens a virtual crafting table
    aliases: [crafting, wb, workbench]
  anvil:
    description: Opens a virtual anvil
  enderchest:
    description: Opens a virtual enderchest
    aliases: [ec, echest]
  near:
    description: Shows you all players nearby
  blocks:
    description: Condenses all gems in your inventory into blocks
    aliases: [condense]
  disposal:
    description: Opens a disposal GUI to dispose your un-wanted goods
    aliases: [dispose, trash]
  feed:
    description: Fills your food level instantly
    aliases: [food, hunger, fillhunger]
  nightvision:
    description: Toggles if you can see in the dark or not
    aliases: [nv]
  fix:
    description: Repairs your items
    aliases: [repair]
  speed:
    description: Makes you faster flying and walking
  tptoggle:
    description: Toggles if you can receive tpa requests or not
    aliases: [tpatoggle, teleporttoggle]
  msgtoggle:
    description: Toggles if you can receive private messages or not
    aliases: [pmtoggle, messagetoggle, messagestoggle]
  rename:
    description: Renames the item you are holding in hand
  heal:
    description: Heals yourself
  clearinventory:
    description: Clears your inventory
    aliases: [ci, clear, clearinv]
  cartographytable:
    description: Opens a virtual cartographytable
  grindstone:
    description: Opens a virtual grindstone
  loom:
    description: Opens a virtual loom
  smithingtable:
    description: Opens a virtual smithing table
  stonecutter:
    description: Opens a virtual stonecutter
  playertime:
    description: Changes your personal time
    aliases: [ptime]
  xpbottle:
    description: Converts your current exp into xp bottles
    aliases: [xpbottles, expbottle, expbottles]
  broadcast:
    description: Broadcasts a message to all players
    aliases: [announce,announcement,bc]
  vanish:
    description: Toggles if you are invisible or not
    aliases: [v]
  restart:
    description: Restarts the server with a countdown
    aliases: [stop, shutdown]