name: ClymeSkyblockCore
version: 1.0
api-version: 1.16
author: CAMOU
website: https://misi.solutions/
main: solutions.misi.clymeskyblockcore.ClymeSkyblockCore
depend:
  - SuperiorSkyblock2
  - WorldGuard

commands:
  spawn:
    description: Teleports you to the spawn
  money:
    description: Shows your current balance
    aliases: [economy, econ, bal, balance, mon]