name: ClymeSkyblockCore
version: 1.0
api-version: 1.16
author: CAMOU
website: https://misi.solutions/
main: solutions.misi.clymeskyblockcore.ClymeSkyblockCore
depend:
  - SuperiorSkyblock2
  - WorldGuard
  - UltraMinions
loadbefore:
  - TAB

commands:
  spawn:
    description: Teleports you to the spawn
  money:
    description: Shows your current balance
    aliases: [economy, econ, bal, balance, mon]
  playtime:
    description: Shows your current playtime
    aliases: [pt, time, playingtime, onlinetime, ot]
  staffpanel:
    description: Opens the Staffpanel
    aliases: [sp, adminpanel, ap, helperpanel, modmenu, modpanel, adminmenu, staffmenu]
  minions:
    description: Opens the Minions Shop
    aliases: [minion]
  menu:
    description: Opens the Server Menu
    aliases: [help]
  crate:
    description: Teleports you to the crates
    aliases: [crates]