name: ClymeSkyblockCore
version: 1.0
api-version: 1.16
author: CAMOU
website: https://misi.solutions/
main: solutions.misi.clymeskyblockcore.ClymeSkyblockCore
depend:
  - SuperiorSkyblock2
  - WorldGuard
  - UltraMinions
  - PlaceholderAPI
loadbefore:
  - TAB
  - AuctionGUIPlus
  - DailyBonus

commands:
  spawn:
    description: Teleports you to the spawn
  money:
    description: Shows your current balance
    aliases: [economy, econ, bal, balance, mon]
  playtime:
    description: Shows your current playtime
    aliases: [pt, time, playingtime, onlinetime, ot]
  staffpanel:
    description: Opens the Staffpanel
    aliases: [sp, adminpanel, ap, helperpanel, modmenu, modpanel, adminmenu, staffmenu]
  minions:
    description: Opens the Minions Shop
    aliases: [minion]
  menu:
    description: Opens the Server Menu
    aliases: [help]
  crate:
    description: Teleports you to the crates
    aliases: [crates]
  farming:
    description: Teleports you to the farming world
    aliases: [farm, resources, resource, mining, farmworld]
  message:
    description: Sends a private messsage to another player
    aliases: [msg, pm, mail]
  reply:
    description: Replies to the players you messaged with recently
    aliases: [r]
  tpa:
    description: Sends a teleport request to a player
  tpaccept:
    description: Accepts a teleport request
    aliases: [tpaaccept]
  tpdeny:
    description: Denies a teleport request
  tpahere:
    description: Sends a request to teleport a player to you
  home:
    description: Opens the Home Menu
    aliases: [sethome, homes]
  gamemode:
    description: Changes your or someones current gamemode
    aliases: [gm]
  pvp:
    description: Teleports you to the pvp arena
    aliases: [fight, pvparena, battle]
  day:
    description: Sets the time to day
  night:
    descriptioN: Sets the time to night
  sun:
    description: Sets the weather to sunny
  rain:
    description: Sets the weather to raining
    aliases: [storm, thunder]
  clymecrystal:
    description: Gives you the clyme crystal
  cosmetics:
    description: Opens the cosmetics menu
    aliases: [pc, cosmetic, gadgets, pets, procosmetics]
  baltop:
    description: Teleports you to the richest players leaderboard
    aliases: [moneytop, ecotop, balancetop, economytop]
  donation:
    description: Plays the donation effect to all players