name: ClymeSkyblock
version: 1.0
api-version: 1.15
author: CAMOU
website: https://misi.solutions/
main: solutions.misi.clymeskyblock.ClymeSkyblock

commands:
  spawn:
    description: Teleports you to the spawn